(define (choices menu)
  (if (null? menu)
      '(())
      (let ((smaller (choices (cdr menu))))
        (reduce append (map (lambda (item)
                              (map (lambda (choice)
                                     (se item choice))
                                   smaller))
                            (car menu))))))
