(define (phone-spell num)
  (if (= (count num) 1)
      (number-letters num)
      (append-every-every (number-letters (last num))
			  (phone-spell (bl num)))))

(define (append-every-every letters sent)
  (if (empty? sent)
      '()
      (se (append-letters-helper letters (first sent))
	  (append-every-every letters (bf sent)))))

(define (append-letters-helper letters wd)
  (if (empty? letters)
      '()
      (se (word wd (first letters))
	  (append-letters-helper (bf letters) wd))))

(define (number-letters num)
  (cond ((= num 2) '(a b c))
	((= num 3) '(d e f))
	((= num 4) '(g h i))
	((= num 5) '(j k l))
	((= num 6) '(m n o))
	((= num 7) '(p q r s))
	((= num 8) '(t u v))
	((= num 9) '(w x y z))))