(define (roman-value letter)
  (cond ((equal? letter 'i) 1)
	((equal? letter 'v) 5)
	((equal? letter 'x) 10)
	((equal? letter 'l) 50)
	((equal? letter 'c) 100)
	((equal? letter 'd) 500)
	((equal? letter 'm) 1000)
	(else 'huh?)))

(define (arabic wd)
  (cond ((empty? wd) 0)
	((empty? (bf wd)) (roman-value (first wd)))
	(else (if (< (roman-value (first wd)) (roman-value (first (bf wd))))
		  (+ (- (roman-value (first (bf wd))) (roman-value (first wd)))
		     (arabic (bf (bf wd))))
		  (+ (roman-value (first wd)) 
		     (arabic (bf wd)))))))