(define (phone-letter-to-number letter)
  (cond ((member? letter '(a b c)) 2)
	((member? letter '(d e f)) 3)
	((member? letter '(g h i)) 4)
	((member? letter '(j k l)) 5)
	((member? letter '(m n o)) 6)
	((member? letter '(p q r s)) 7)
	((member? letter '(t u v)) 8)
	((member? letter '(w x y z) 9))
	(else 'wrong-letter)))

(define (phone-unspell wd)
  (accumulate word (every phone-letter-to-number wd)))