(define (same-shape? sent1 sent2)
  (cond ((and (empty? sent1) (empty? sent2)) #t)
	((and (not (empty? sent1)) (empty? sent2)) #f)
	((and (empty? sent2) (not (empty? sent2))) #f)
	((not (= (count (first sent1)) (count (first sent2)))) #f)
	(else (same-shape? (bf sent1) (bf sent2)))))