(define (shuffle1 lst)
  (define (loop in out n)
    (if (= n 0)
	(cons (car in) (shuffle1 (append (cdr in) out)))
	(loop (cdr in) (cons (car in) out) (- n 1))))
  (if (null? lst)
      '()
      (loop lst '() (random (length lst)))))